### ISSUE TITLE
Meaning of `.reset()`?

### ISSUE THREAD

**Issue by wbrickner** [pkalivas/radiate#16]
# What does `.reset()` method do on `Neat` struct?

I'd like to ensure my understanding is correct, as the documentation is a little unclear.

My real goal is to remove any previous state that may be retained in the network from previous evaluations / forward passes.
This ensures there is no chance of information leakage between successive trials (fitness measurements).

Will the `.reset()` method do this?

Thank you!

**Comment by pkalivas** [comment]
Correct, the ```.reset()``` method will clear all memory/previous state from the NEAT network.
