### ISSUE TITLE
How to evolve based on head to head battles?

### ISSUE THREAD

**Issue by travis-leith** [pkalivas/radiate#20]
If I want to evolve organisms that compete in head to head 2 player contests (like tic tac toe), is there any guidence on how to set this up. An example would be great. I note that the sovle funtion for the Problem trait has a parameter for only a single model. Is there a convenient way to set up 2 player games?

**Comment by pkalivas** [comment]
I took a break from this project but am back actively developing it. The library has major breaking changes (complete rehaul of the lib). I am closing this issue, but go ahead and open a new one if you are still looking for a solution. The new architecture would be able to handle your above question.
